version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hyro
    overwrite: true

permissions:
  - object: /
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user