version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing app dependencies...
      - npm install
  build:
    commands:
      - echo Building static site...
      - npm run build

artifacts:
  files:
    - build/**/*
    - public/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
  base-directory: ./

cache:
  paths:
    - './node_modules/**/*'