name: Upload to S3 Bucket
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@main

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      # 폴더 생성
      - name: Make artifacts directory
        run: mkdir ./artifacts/

      - name: Make zip file
        run: zip -r ./artifacts/build.zip ./build/* ./scripts/* appspec.yml
        shell: bash

      # 자격 증명
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 업로드
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://hyro-web/build/build.zip

      - name: Trigger CodeDeploy
        env:
          AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          Default region name: 'ap-northeast-2'
        run: aws deploy create-deployment --application-name hyro-web-code-deploy --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name hyro-web-deploy-group --region ap-northeast-2 --s3-location bucket=hyro-web,bundleType=zip,key=build/build.zip

